# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from random import randint
from random import seed
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSurvey1():
  def setup_method(self):
    self.driver = webdriver.Chrome(executable_path=r"./chromedriver")
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_survey1(self):
    # Test name: survey1
    # Step # | name | target | value | comment
    # 1 | open | http://demos.rsamanez.com/questionnaire-survey/surveys/2-second-cool-title |  | 
    self.driver.get("http://demos.rsamanez.com/questionnaire-survey/surveys/2-second-cool-title")
    # 2 | setWindowSize | 1470x830 |  | 
    self.driver.set_window_size(1470, 830)
    # 3 | click | css=label:nth-child(1) > .list-group-item |  |
    item = randint(1, 4)
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(" + str(item) + ") > .list-group-item").click()
    # 4 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 5 | type | id=name | Selenium Tester | 
    self.driver.find_element(By.ID, "name").send_keys("Selenium Tester")
    # 6 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 7 | type | id=email | selenium@test.com | 
    self.driver.find_element(By.ID, "email").send_keys("selenium@test.com")
    # 8 | click | css=.btn |  |
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

seed(1)
test1 = TestSurvey1()
test1.setup_method()
test1.test_survey1()
test1.teardown_method()