# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSurvey1():
  def setup_method(self):
    self.driver = webdriver.Remote(command_executor='http://10.0.0.9:10000/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_survey1(self):
    self.driver.get("http://demos.rsamanez.com/questionnaire-survey/surveys/2-second-cool-title")
    self.driver.set_window_size(1470, 830)
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(1) > .list-group-item").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Selenium Tester")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("selenium@test.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
test1 = TestSurvey1()
test1.setup_method()
test1.test_survey1()
test1.teardown_method()