# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsurvey():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsurvey(self):
    self.driver.get("https://demos.rsamanez.com/questionnaire-survey/")
    self.driver.set_window_size(1470, 830)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1)").click()
    self.driver.find_element(By.ID, "email").send_keys("rsamanez@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(1) p font > font").click()
    self.driver.find_element(By.ID, "answer43").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) label:nth-child(2) font > font").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Selenium Tester")
    self.driver.find_element(By.ID, "email").send_keys("selenium@test.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-dark > font > font").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
