# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from random import seed
from random import randint
from datetime import datetime

class TestLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://demos.rsamanez.com/qs/")
    #self.driver.set_window_size(1603, 830)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-body").click()
    self.driver.find_element(By.ID, "email").send_keys("rsamanez@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Relacion Laboral").click()
    self.driver.find_element(By.LINK_TEXT, "Q-S").click()
    self.driver.find_element(By.CSS_SELECTOR, "a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()

def run_test():
  seed(datetime.now())
  my_delay = randint(0, 60)
  print(str(my_delay) + "\n")
  if my_delay < 61:
    time.sleep(my_delay)
    test1 = TestLogin()
    test1.setup_method()
    test1.test_login()
    test1.teardown_method()


while (1):
  my_wait = randint(0, 240)
  time.sleep(my_wait)
  run_test()