# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from random import seed
from random import randint
from datetime import datetime

class TestTestOne():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_testOne(self):
    # Test name: TestOne
    # Step # | name | target | value | comment
    # 1 | open | /dev/ |  | 
    self.driver.get("https://s32jqca7jl.execute-api.us-east-1.amazonaws.com/dev/")
    # 2 | setWindowSize | 1603x830 |  | 
    self.driver.set_window_size(1603, 830)
    # 3 | click | name=money |  | 
    self.driver.find_element(By.NAME, "money").click()
    # 4 | type | name=money | 100 |
    amount = randint(1, 1000)
    self.driver.find_element(By.NAME, "money").send_keys(str(amount))
    # 5 | sendKeys | name=money | ${KEY_ENTER} |
    time.sleep(1)
    self.driver.find_element(By.NAME, "money").send_keys(Keys.ENTER)
    time.sleep(2)

def run_test():
    seed(datetime.now())
    my_delay = randint(0,60)
    print( str(my_delay) + "\n")
    if my_delay < 56 :
      time.sleep(my_delay)
      test1 = TestTestOne()
      test1.setup_method()
      test1.test_testOne()
      test1.teardown_method()
while (1):
    my_wait = randint(0,180)
    time.sleep(my_wait)
    run_test()
    

  
