# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestXxx():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_xxx(self):
    # Test name: xxx
    # Step # | name | target | value | comment
    # 1 | open | http://demos.rsamanez.com/questionnaire-survey/surveys/2-second-cool-title |  | 
    self.driver.get("http://demos.rsamanez.com/questionnaire-survey/surveys/2-second-cool-title")
    # 2 | setWindowSize | 1603x830 |  | 
    self.driver.set_window_size(1603, 830)
    # 3 | click | css=.card:nth-child(2) label:nth-child(1) > .list-group-item |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) label:nth-child(1) > .list-group-item").click()
    # 4 | click | css=.card:nth-child(3) label:nth-child(2) > .list-group-item |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) label:nth-child(2) > .list-group-item").click()
    # 5 | click | css=.card:nth-child(4) label:nth-child(3) > .list-group-item |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(4) label:nth-child(3) > .list-group-item").click()
    # 6 | click | css=.card:nth-child(5) label:nth-child(4) > .list-group-item |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(5) label:nth-child(4) > .list-group-item").click()
    # 7 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 8 | type | id=name | Selenium Tester | 
    self.driver.find_element(By.ID, "name").send_keys("Selenium Tester")
    # 9 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 10 | type | id=email | selenium@test.com | 
    self.driver.find_element(By.ID, "email").send_keys("selenium@test.com")
    # 11 | click | css=.btn-dark |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-dark").click()
  
